### ISSUE TITLE
Our Friends missing from Home page

### ISSUE THREAD

**Issue by fredworld** [davidmclifton/CASWebsite#10]
NLT, BMVO, SKIES UNLIMITED, Also, Shameless Self Promotion link to Cafe Press for CAS items.

**Comment by davidmclifton** [comment]
Question - are we ok to post promoting links to the sites of organizations that are not the same type of not for profit that we are seeking to become, or does having links to commercial and other interests potentially impact the club's ability to achieve the designation?

**Comment by davidmclifton** [comment]
This is on hold until we learn more about any issue it could cause with our 501c7 filing.
