### ISSUE TITLE
Dark Sites Page

### ISSUE THREAD

**Issue by fredworld** [davidmclifton/CASWebsite#19]
Spruce Knob is missing: http://www.cleardarksky.com/c/spruce_WVkey.html?1
79° 31' 49" W; 38° 42' 07" N 
![spruceknob](https://cloud.githubusercontent.com/assets/20790098/18936281/082ffe52-85b4-11e6-879e-6e89132be7e1.jpg)
The set-up area is where the more centered "104" is.

Arguably, the darkest observing site on the East Coast. Can be windy, cold, dewy and utterly glorious when it's calm and clear with velvet black skies horizon to horizon, devoid of any light encroachment whatsoever. One can have difficulty finding constellations as so many stars are visible. The Milky Way can be bright with shadows casting when things are right.

**Comment by davidmclifton** [comment]
Done
