### ISSUE TITLE
Observing Report Disappeared 

### ISSUE THREAD

**Issue by fredworld** [davidmclifton/CASWebsite#20]
Observing report I posted and the reposted has disappeared. Should be the 1st post in this thread: https://www.chesmontastro.org/forums/topic/bmvo-feb-19-and-26-2017/#post-1706

**Comment by davidmclifton** [comment]
Crazy - I will look into it.

**Comment by davidmclifton** [comment]
This was marked as spam by Akismet. Should be resolved.
